# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install linter
      run: |
        curl -sSL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.50.1

    - name: Install dependencies
      run: make vendors

    - name: Run fmt
      run: make fmt

    - name: Run lint
      run: make lint

    - name: Run test-noasm
      run: make test-noasm

    - name: Run test-amd64
      run: make test-amd64
